export type {CardLink} from './home/CardLink.interface'
export type {ProfileInformation} from './home/ProfileInformation.interface'
export type {InfoLinks} from './home/InfoLinks.interface'
export type {ColorOptions} from './home/Links/ColorOptions.interface'
export type {SocialOptions} from './home/Profile/SocialOptions.interface'
export type {ColorBg} from './home/ColorBg.interface'
export type {StyleButton} from './home/StyleButton.interface'