name: Test Login
on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Intentar login con el secret
        run: |
           curl -X POST https://assessment-lit-accidents-strengths.trycloudflare.com/api/login \
            -H "Content-Type: application/json" \
            -d '{"username": "AAMLA", "password": "'"${{ secrets.CHESA_SIA_PASSWORD }}"'"}'
