name: Test Login
on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Intentar login con el secret
        run: |
          USER="AAMLA"
          PASS="${{ secrets.CHESA_SIA_PASSWORD }}"
          echo "Probando login con $USER"
          curl -u "$USER:$PASS" http://localhost:3000/api/login
